# Log4j
logging:
  config: classpath:logback-${spring.profiles.active}.xml
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
# OpenAPI - Naver
openapi:
  naver:
    clientID: xxxx
    clientSecret: xxxxx
    url: https://openapi.naver.com/v1/search/book_adv
# AEC
inf:
  hist:
    aes-key: b3edr6ce00eadc3a
    endpoint: http://xxxx

# SSO
sso:
  hist-url: https://xxxxx

# micrometer prometheus
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    export:
      prometheus:
        enabled: true

spring:
  application:
    name: bcheck-api
  profiles:
    active: local
  jpa:
    show-sql: true

server:
  servlet:
    context-path: /app
  port: 7777

# add for api gateway
aws:
  ses:
    from: mjoung@hist.co.kr

---
spring:
  config:
    activate:
      on-profile: local
  mongo:
    user: xxxx
    password: xxxxx
    port: 27017
    host: bcheck-docdb.cluster-cfe0kcb9osrg.ap-northeast-2.docdb.amazonaws.com
    database: xxxx
# open api
springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    tags-sorter: alpha
    display-request-duration: true
    groups-order: desc
---
spring:
  config:
    activate:
      on-profile: dev
  mongo:
    user: xxxx
    password: xxxxx
    port: 27017
    host: bcheck-docdb.cluster-cfe0kcb9osrg.ap-northeast-2.docdb.amazonaws.com
    database: xxxx
# open api
springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    tags-sorter: alpha
    display-request-duration: true
    groups-order: desc
---
spring:
  config:
    activate:
      on-profile: prd
  pid:
    file: bcheck.pid
  mongo:
    user: xxxx
    password: xxxxx
    port: 27017
    host: bcheck-docdb.cluster-cfe0kcb9osrg.ap-northeast-2.docdb.amazonaws.com
    database: xxxx
# open api
springdoc:
  api-docs:
    enabled: false